// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// sdp1_admm
List sdp1_admm(arma::mat As, int K, List opts);
RcppExport SEXP sbmSDP_sdp1_admm(SEXP AsSEXP, SEXP KSEXP, SEXP optsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::mat >::type As(AsSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< List >::type opts(optsSEXP);
    __result = Rcpp::wrap(sdp1_admm(As, K, opts));
    return __result;
END_RCPP
}
